### ISSUE TITLE
Ospec - Errors inside tests swallowed up

### ISSUE THREAD

**Issue by jonahx** [lhorie/mithril.js#1798]
I believe this is a bug.

To reproduce, run:

``` javascript
const o = require('ospec')

o('Swallowed Error', function() {
  o(1+1).equals(2)
  throw 'swallowed error'
})

o.run()
```
When executed directly, this file prints the following error, no matter what the original error is:
```
:!node /Users/jg/Documents/projects/pokerquiz/tests/ospec_bug.js
/Users/jg/Documents/projects/pokerquiz/node_modules/ospec/ospec.js:211
                                var stackTrace = r.error.match(/^(?:(?!Error|[\/\\]ospec[\/\\]ospec\.js).)*$/m)
                                                        ^

TypeError: Cannot read property 'match' of undefined
    at report (/Users/jg/Documents/projects/pokerquiz/node_modules/ospec/ospec.js:211:29)
    at next (/Users/jg/Documents/projects/pokerquiz/node_modules/ospec/ospec.js:108:6)
    at next (/Users/jg/Documents/projects/pokerquiz/node_modules/ospec/ospec.js:97:7)
    at series (/Users/jg/Documents/projects/pokerquiz/node_modules/ospec/ospec.js:69:4)
    at test (/Users/jg/Documents/projects/pokerquiz/node_modules/ospec/ospec.js:48:4)
    at Function.o.run (/Users/jg/Documents/projects/pokerquiz/node_modules/ospec/ospec.js:43:3)
    at Object.<anonymous> (/Users/jg/Documents/projects/pokerquiz/tests/ospec_bug.js:10:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)

shell returned 1
```
When executed through the npm `ospec` command, ospec prints nothing, and just hangs, until you kill it with ctrl-C:
```
/Documents/projects/pokerquiz (master) $ npm run ospec

> @ ospec /Users/jg/Documents/projects/pokerquiz
> ospec

^C
~/Documents/projects/pokerquiz (master) $ 
```

**Comment by isiahmeadows** [comment]
What's your `"ospec"` npm script look like?

**Comment by jonahx** [comment]
It's literally `ospec`.  That is, it calls the binary that comes with the package.

**Comment by isiahmeadows** [comment]
Check if `console.log` within the tests is stripped.

**Comment by jonahx** [comment]
It is not stripped.

**Comment by isiahmeadows** [comment]
Is `console.error` stripped? I suspect it won't be, but I'm not sure.

**Comment by isiahmeadows** [comment]
Part of why I'm confused is because it doesn't respawn Node before running the tests.

**Comment by jonahx** [comment]
To update based on our gitter conversation, it seems that using the ospec version from mithril#next fixes the _2nd_ problem, ie, ospec silently hanging.

However, the first problem -- that all error are reported as a generic `TypeError: Cannot read property 'match' of undefined` results from a still extant ospec bug: namely, that ospec assumes all errors are js `Error` objects, so that errors which result from `throw 'some error description` (or anything else that results in a primitive string "error" rather than an `Error` object, if alternate causes exist) will be reported as the above type error because of this:

```
	function record(message, error) {
		var result = {pass: message === null}
		if (result.pass === false) {
			if (error == null) {  // <-- HANDLES null, but not a "string" error
				error = new Error
				if (error.stack === undefined) new function() {try {throw error} catch (e) {error = e}}
			}
			result.context = subjects.join(" > ")
			result.message = message
			result.error = error.stack
		}
		results.push(result)
	}
```
A one line-fix results in the correct error being reported:
```
			if (error == null || typeof error === 'string') {
```
although without a stack trace.  However, I'm not sure it's possible to access the stack trace with string errors.  The above is at least somewhat helpful.

One final note: These errors stop processing completely, rather than finishing the remaining tests.  I'm not sure if this is intended.  Personally, I think reporting the test as failed with the error, and then continuing to process the remaining tests, would be preferable.  This may be a bigger change.
